---
name: CI checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Migrate database
        run: |
          cp .env.example .env
          mkdir data
          cargo install sqlx-cli --no-default-features --features sqlite,native-tls
          sqlx database create
          sqlx migrate run
      - name: Clippy
        run: |
          rustup component add clippy --toolchain nightly
          cargo clippy
          cargo clippy --all-features
      - name: Build
        run: cargo build --release --features multitenant
      - name: Push to package.cosmian.com
        run: |
          set -x
          echo "$PACKAGE_SSH_KEY" > ~/id_rsa
          chmod 600 ~/id_rsa
          DESTINATION_DIR=/mnt/package/findex_cloud/last_build
          ssh -i ~/id_rsa -o "StrictHostKeyChecking no" cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp -i ~/id_rsa -o "StrictHostKeyChecking no" target/release/findex_cloud cosmian@package.cosmian.com:$DESTINATION_DIR/
          rm ~/id_rsa
        env:
          PACKAGE_SSH_KEY: ${{ secrets.PACKAGE_SSH_KEY }}
